FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Dosyaları kopyala ve restore et
COPY *.csproj ./
RUN dotnet restore

# Yayınla
COPY . ./
RUN dotnet publish -c Release -o out

# Çalıştırma ortamı
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "CryptoPulse.API.dll"]